### ISSUE TITLE
Allow multiple arbitrary URL params in endpoints

### ISSUE THREAD

**Issue by LakiG** [ga4gh/openapi-test-runner#42]
The schema check on test file validates the endpoints like `/tasks/{id}`. The value of {id} is extracted from `storage_vars`.
While storing multiple variables such as `{id1}` & `{id2}` and using them as URL params such as `/tasks/{id1}` & `/tasks/{id2}`, they fail at schema check.

- [ ] Allow arbitrary variables to be used as URL parameters.
- [ ] Keep the schema check enabled for endpoints.

Proposed Solution:
Add a new field in test file called ~~`url_parameters`~~ `path_parameters`. Key - actual URL param. Value - the storage variable.
Example - 
```
  ...
  storage_vars:
    id1: 1234
- name: get_task
  endpoint: /tasks/{id}
  path_parameters:
    id: {id1}
  ...
```
