### ISSUE TITLE
Store response fields as user defined variables

### ISSUE THREAD

**Issue by LakiG** [ga4gh/openapi-test-runner#8]
**Issue/Current Implementation**
Fields like ID are extracted from Create Task response and saved for further usage in Get task or Cancel Task.
It is embedded in the code and not abstract. 
Dependent on the API Specification and has to be handled individually for every field.

**Goal**
Handle from the YAML test file.

**Suggestion**
```
jobs:
  - name: create_task
    ...
    storage_vars:
      id: response["id"]
```

`storage_vars` is the property for each job.
`id` (Key) is the variable reference name.
`response["id"]` (Value) is the expected field to extract from the response.
